### ISSUE TITLE
compile-styles error 

### ISSUE THREAD

**Issue by rybajz** [webrouse/n-sandbox#1]
Hi,
I am playing with your amazing sandbox, but I am getting following error in compiling: 
ReferenceError: inlineSvgSass is not defined
    at D:/www/Nette/Webrouse/gulpfile.babel.js:229:12
    at Array.map (<anonymous>)
    at Gulp.<anonymous> (D:/www/Nette/Webrouse/gulpfile.babel.js:184:36)
    at module.exports (D:\www\Nette\Webrouse\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\www\Nette\Webrouse\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\www\Nette\Webrouse\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\www\Nette\Webrouse\node_modules\orchestrator\index.js:134:8)
    at C:\Users\rybar\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:54:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Could you please help me to solve this problem?

Many thanks

**Comment by michaljurecko** [comment]
Hi,

Thank you for your interest.

Can you please send me your `nodejs --version` output?

**Comment by rybajz** [comment]
Hi,
my version is 8.5.0

**Comment by michaljurecko** [comment]
It's probably due to innovations in nodejs. 

The problem is that the missing functions are defined later. 

Until I fix it and test it with newer versions of nodejs,   
**try to move the helpers functions before the tasks** (to the beginning of the `gulpfile.babel.js`):
https://github.com/webrouse/n-sandbox/blob/e73aa6fd7b2f312406264acc94848f26bd798338/gulpfile.babel.js#L566-L842

**Comment by michaljurecko** [comment]
After updating dependencies, it works: https://github.com/webrouse/n-sandbox/commit/a0a5ad4f0b01628f6a0744b4b36502f28b8b99f6

**Tested with:**
`nodejs -v`: v8.9.3
`npm -v`: 5.6.0
